name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV
      shell: bash

    - name: Install dependencies
      run: |
        source $HOME/.poetry/env
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: true
        POETRY_VIRTUALENVS_IN_PROJECT: true

    - name: Run migrations
      run: |
        source $HOME/.poetry/env
        poetry run python manage.py migrate

    - name: Run tests
      run: |
        source $HOME/.poetry/env
        poetry run python manage.py test
